[passwords]
"Sajib" = "123"
"sajib" = "test1"
"Lucalicata@test.com" = "test123"
"Esteban@test.com" = "testxyz"
"sibtain@langdalecarehomes.co.uk" = "Langdale2024!"
"amaan@langdalecarehomes.co.uk"="Langdale2024!"
"sajjad@langdalecarehomes.co.uk"="Langdale2024!"
"neemat@langdalecarehomes.co.uk"="Langdale2024!"
"zishan@langdalecarehomes.co.uk"="Langdale2024!"
